- name: dotfiles
  git:
    repo: git@github.com:hongtron/dotfiles.git
    dest: ~/dotfiles
    update: false

- name: iTerm custom settings file
  osx_defaults:
    domain: com.googlecode.iterm2
    key: PrefsCustomFolder
    type: string
    value: "{{ ansible_env.PWD }}/roles/ali_mac/files"
