homebrew_taps: []

homebrew_package_removals: []

homebrew_packages:
- autoconf
- autojump
- automake
- bazaar
- cloc
- coreutils
- cowsay
- enchant
- exiftool
- fd
- fdupes
- ffmpeg
- freetype
- fswatch
- gdal
- gdbm
- git
- github/gh/gh
- goaccess
- gpg
- graphicsmagick
- heroku/brew/heroku
- hub
- hyperfine
- inetutils
- jhead
- jpeg
- jpegoptim
- jq
- lesspipe
- libevent
- libmemcached
- libpng
- libtool
- libyaml
- memcached
- myrepos
- ncdu
- nginx
- nvm
- openssl
- ossp-uuid
- pandoc
- parallel
- percona-toolkit
- pkg-config
- pngcrush
- postgresql
- pwgen
- pyenv
- pypy
- python
- qpdf
- readline
- rsync
- rtmpdump
- ruby
- ruby-build
- ruby-install
- sd
- shellcheck
- sqlite
- swig
- tree
- watch
- wget
- xz
- zlib
- zsh-completions

homebrew_cask_packages:
- alfred
- calibre
- discord
- docker
- firefox
- google-chrome
- iterm2
- java
- karabiner-elements
- rectangle
- silverlight
- skim
- vlc

gem_packages:
- bundler
